### ISSUE TITLE
Pending changes to defaults r-base packages

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/r-base-feedstock#34]
The `r-base` packages in the `r` channel and in https://repo.continuum.io/pkgs/r will be patched in the coming days to make room for the addition of MRO packages to the channel.  The central problem is that we need to provide exclusivity between the `r-base` package and an `mro-base` package; they cannot be installed into the same environment, due to overlapping paths.

We've considered *many* technical solutions to this problem, including changes to conda, and we've arrived at the solution that requires us to patch metadata of the `r-base` package.  Specifically, we have to add one additional dependency--a package that allows us to enforce the exclusivity.

Specifically, we're adding an additional package to the `r` channel with the following `meta.yaml`

```
package:
  name: _r-mutex
  version: 1.0.0

build:
  string: anacondar_1
  number: 1
  track_features:
    - anacondar

about:
  license: BSD
  summary: A mutex package to ensure environment exclusivity between Anaconda R and MRO.
```

(There's a similar `_r-mutex` package that we're using for mro, just with a different build string.)

All `r-base` packages will now include, or be patched to include

    "_r-mutex 1.* anacondar_1"

in the depends list.

Without this step, users will often end up with both `r-base` and `mro-base` installed in the same environment.

For the `r` channel, I'm working on a script that will just download the package, patch the metadata, and then re-upload the package in place.  We're doing this with the understanding that it *will* change the md5 of the package, and so it could raise alarms for people mirroring repositories.  It's the least bad of all the alternatives we have right now though.

If the conda-forge community wants to use my script, I'll be happy to share it.

If instead the community wants to take the route of just rebuilding the packages, it'll be necessary to remove the `main` tag on anaconda.org from any `r-base` packages without `"_r-mutex 1.* anacondar_1"` in the dependency list.

We'll likely be releasing the MRO packages in the `r` and https://repo.continuum.io/pkgs/r `defaults` channel early next week.
